# Goal: To build cicd pipeline (just dummy)

name: CI/CD
on:
  push:
    branches: [main]

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v4

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build the code with Docker
        uses: docker/setup-buildx-action@v3

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: testing the code
        run: echo "test done"

  deploy:
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo "deployment has done"


  
